name: Preprocessing

on:
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install -r requirements.txt

      - run: python preprocessing/automate_AkiraRianSatyaDhamma.py

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update preprocessed dataset
